## Loading and preprocessing the data  

```{r echo = TRUE}
if (!file.exists("data")) {
  dir.create("data")
} else {
  print("Folder data exists!")
}

fileURL <- c("http://d396qusza40orc.cloudfront.net/repdata/data/activity.zip")
download.file(fileURL, destfile = ".\\data\\activity.zip")

zipFile <- c(".\\data\\dataset.zip")
unzip(zipFile, exdir = ".\\data")
ActFile <- c(".\\data\\activity.csv")
data1 <- read.csv(ActFile, header = TRUE, stringsAsFactors = FALSE)
```

## What is mean total number of steps taken per day?
```{r echo = TRUE}
dfa <- aggregate(steps ~ date, data = data1, FUN = sum)
hist(dfa$steps, col = "red", main = "Total number of steps taken each day", xlab = "Steps")
mean(dfa$steps)
median(dfa$steps)
```

## What is the average daily activity pattern?
```{r echo = TRUE}
dfa2 <- aggregate(steps ~ interval, data = data1, FUN = mean)
require(ggplot2)
ggplot(data = dfa2, aes(interval, steps)) + geom_line()
dfa2[max(dfa2$steps), ]
```

## Imputing missing values
```{r echo = TRUE}
dfa3 <- subset(data1, is.na(steps))
nrow(dfa3)
for (i in which(sapply(data1, is.numeric))) {data1[is.na(dd[,i]),i] <- mean(data1[,i], na.rm = TRUE)}
dfa4 <- aggregate(steps ~ date, data = data1, FUN = sum)
hist(dfa4$steps, col = "red", main = "Total number of steps taken each day", xlab = "Steps")

mean(dfa4$steps)
median(dfa4$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r echo = TRUE}

```